image: bradrydzewski/go:1.4
git:
  path: github.com/rkgo/timeout
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
script:
  - make deps
  - make test
notify:
  email:
    recipients:
      - m+rkgo@rkusa.st